/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/target.glb 
Author: Kae Games Official (https://sketchfab.com/kaelynb475)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/target-bnc-bike-fighter-86bc7638c3e64d47b77b416106953da2
Title: Target Bnc bike fighter
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/target.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[Math.PI, 0, Math.PI / 2]} scale={100}>
            <mesh geometry={nodes.Cylinder_Material229_0.geometry} material={materials['Material.229']} />
            <mesh geometry={nodes.Cylinder_Material230_0.geometry} material={materials['Material.230']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/target.glb')
